/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'light-bg': '#F9F9F9',
        'dark-bg': '#252128',
        'line-bg': '#BAB2E7',
        'hd-modeback-lg': '#4731D3',
        'hd-modeset-lg': '#FFE86E',
        'hd-modetxt-lg': '#777777',
        'hd-modeback-drk': '#3A3A3A',
        'hd-modetxt-drk': '#D9D9D9',
        'hd-logoback-lg': '#EEEBFF',
        'hd-logotxt-lg': '#7B61FF',
        'hd-logoback-drk': '#4731D3',
        'hd-logotxt-drk': '#8F88FF',
        'hd-hireback': '#FFFFFF',
        'hd-hiretxt': '#3730A3',
        'hr-nametxt-lg': '#4338CA',
        'hr-nametxt-drk': '#B7AAFF',
        'hr-headertext-lg': '#1F2937',
        'hr-headertext-drk': '#AEBCCF',
        'hr-alttext-lg': '#6B7280',
        'hr-alttext-drk': '#FFFFFF',
        'hr-hirebg-lg': '#3730A3',
        'hr-hirebg-drk': '#FFFFFF',
        'hr-hiretext-lg': '#FFFFFF',
        'hr-hiretext-drk': '#000000',
        'hr-btnbg-lg': '#FFFFFF',
        'hr-btnbg-drk': '#383838',
        'hr-btntxt-lg': '#3730A3',
        'hr-btntxt-drk': '#E1E1FF',
        'sk-headtxt-lg': '#1F2937',
        'sk-headtxt-drk': '#AEBCCF',
        'sk-parthead-lg': '#4338CA',
        'sk-parthead-drk': '#B7AAFF',
        'sk-parttxt-lg': '#6B7280',
        'sk-parttxt-drk': '#FFFFFF',
        'pp-headtxt-lg': '#1F2937',
        'pp-headtxt-drk': '#AEBCCF',
        'pp-alttext-lg': '#4338CA',
        'pp-alttext-drk': '#B7AAFF',
        'pp-text-lg': '#000000',
        'pp-textright-lg': '#6B7280',
        'pp-text-dark': '#FFFFFF',
        'prj-headtxt-lg': '#1F2937',
        'prj-headtxt-drk': '#AEBCCF',
        'prj-alttxt-lg': '#4338CA',
        'prj-alttxt-drk': '#CFCBFF',
        'prj-txt-lg': '#6B7280',
        'prj-txt-drk': '#FFFFFF',
        'prj-btnbg-lg': '#FFFFFF',
        'prj-btnbg-drk': '#383838',
        'prj-btntxt-lg': '#3730A3',
        'prj-btntxt-drk': '#8F88FF',
        'prj-link-drk': '#E1E1FF',
        'prj-bg-drk': '#252128',
        'ftr-bg-lg': '#F9F9F9',
        'ftr-bg-drk': '#141414',
        'ftr-headtxt-lg': '#1F2937',
        'ftr-headtxt-drk': '#AEBCCF',
        'ftr-mail-lg': '#AF0C48',
        'ftr-mail-drk': '#BAB2E7',
        'ftr-personal-lg': '#0A0A14',
        'ftr-personal-drk': '#E1E1FF',
        'ftr-github-lg': '#00AB6B',
        'ftr-github-drk': '#17D18B',
        'ftr-linkedin-lg': '#0077B5',
        'ftr-linkedin-drk': '#0BA6F6',
        

      }
    },
  },
  plugins: [],
}